Repository octopusden/octopus-base, pull requests merged in 2023-06, with the labels that each got.

#53 Support hybrid flow
  .github/workflows/common-java-gradle-release.yml
  .github/workflows/common-java-maven-release.yml
Labels: enhancement

#56 Fix publishing to Nexus
  .github/workflows/common-java-gradle-release.yml
Labels: bug

#54 Comment about TC parameter
  docs/Octopus Infrastructure Administrator Guide.md
Labels: documentation

#58 Add gradle parameters
  .github/workflows/common-java-gradle-release.yml
Labels: bug

#60 Add parameter for event-type
  teamcity.meta-runners/OctopusCallGitHubAction.xml
Labels: enhancement

#61 XML fix
  teamcity.meta-runners/OctopusCallGitHubAction.xml
Labels: bug

#62 Fix metarunner args
  teamcity.meta-runners/OctopusCallGitHubAction.xml
Labels: bug

#65 64 add general docker build and deploy action
  common-docker-build-deploy.yml
  docs/Octopus Developer Guide.md
Labels: documentation, enhancement
