Repository octopusden/octopus-base, pull requests merged in 2023-10, with the labels that each got.

#75 Allow to specify artifact path pattern
  .github/workflows/common-check-artifact.yml
Labels: enhancement

#76 Release registration in octopus-release-log
  .github/workflows/common-check-and-register-release.yml
  .github/workflows/common-java-gradle-release.yml
  .github/workflows/common-register-release.yml
Labels: enhancement

#77 Add 'build' label for a new project
  .github/release.yml
  docs/Octopus Administrator Guide.md
  docs/Octopus Developer Guide.md
Labels: documentation

#80 Gradle release: do not set version of octopus-base for external action
  .github/workflows/common-java-gradle-release.yml
  .github/workflows/common-java-maven-release.yml
Labels: bug
